In [1]:
pip show scikit-learn

Name: scikit-learn
Version: 1.2.2
Summary: A set of python modules for machine learning and data mining
Home-page: http://scikit-learn.org
Author: None
Author-email: None
License: new BSD
Location: /home/ubuntu/environments/hpepyspark/lib/python3.8/site-packages
Requires: scipy, joblib, numpy, threadpoolctl
Required-by: shapash, shap, lightgbm, handyspark, category-encoders, alibi-detect
Note: you may need to restart the kernel to use updated packages.


In [2]:
import pandas as pd

In [3]:
dia = pd.read_csv("https://raw.githubusercontent.com/ismayilsiyad/HPE-AI1/main/Datasets/diabetes.csv")

In [4]:
dia

PatientID  Pregnancies  PlasmaGlucose  DiastolicBloodPressure  \
0        1354778            0            171                      80   
1        1147438            8             92                      93   
2        1640031            7            115                      47   
3        1883350            9            103                      78   
4        1424119            1             85                      59   
...          ...          ...            ...                     ...   
14995    1490300           10             65                      60   
14996    1744410            2             73                      66   
14997    1742742            0             93                      89   
14998    1099353            0            132                      98   
14999    1386396            3            114                      65   

       TricepsThickness  SerumInsulin        BMI  DiabetesPedigree  Age  \
0                    34            23  43.509726          1.213191   21   
1                    47            36  21.240576          0.158365   23   
2                    52            35  41.511523          0.079019   23   
3                    25           304  29.582192          1.282870   43   
4                    27            35  42.604536          0.549542   22   
...                 ...           ...        ...               ...  ...   
14995                46           177  33.512468          0.148327   41   
14996                27           168  30.132636          0.862252   38   
14997                43            57  18.690683          0.427049   24   
14998                18           161  19.791645          0.302257   23   
14999                47           512  36.215437          0.147363   34   

       Diabetic  
0             0  
1             0  
2             0  
3             1  
4             0  
...         ...  
14995         1  
14996         1  
14997         0  
14998         0  
14999         1  

[15000 rows x 10 columns]

In [5]:
dia.isnull().sum()

PatientID                 0
Pregnancies               0
PlasmaGlucose             0
DiastolicBloodPressure    0
TricepsThickness          0
SerumInsulin              0
BMI                       0
DiabetesPedigree          0
Age                       0
Diabetic                  0
dtype: int64

In [6]:
dia.drop("PatientID", axis = 1, inplace=True)

In [7]:
dia.head()

Pregnancies  PlasmaGlucose  DiastolicBloodPressure  TricepsThickness  \
0            0            171                      80                34   
1            8             92                      93                47   
2            7            115                      47                52   
3            9            103                      78                25   
4            1             85                      59                27   

   SerumInsulin        BMI  DiabetesPedigree  Age  Diabetic  
0            23  43.509726          1.213191   21         0  
1            36  21.240576          0.158365   23         0  
2            35  41.511523          0.079019   23         0  
3           304  29.582192          1.282870   43         1  
4            35  42.604536          0.549542   22         0

In [8]:
y = dia["Diabetic"]
X = dia.drop("Diabetic", axis = 1)

In [10]:
X

Pregnancies  PlasmaGlucose  DiastolicBloodPressure  TricepsThickness  \
0                0            171                      80                34   
1                8             92                      93                47   
2                7            115                      47                52   
3                9            103                      78                25   
4                1             85                      59                27   
...            ...            ...                     ...               ...   
14995           10             65                      60                46   
14996            2             73                      66                27   
14997            0             93                      89                43   
14998            0            132                      98                18   
14999            3            114                      65                47   

       SerumInsulin        BMI  DiabetesPedigree  Age  
0                23  43.509726          1.213191   21  
1                36  21.240576          0.158365   23  
2                35  41.511523          0.079019   23  
3               304  29.582192          1.282870   43  
4                35  42.604536          0.549542   22  
...             ...        ...               ...  ...  
14995           177  33.512468          0.148327   41  
14996           168  30.132636          0.862252   38  
14997            57  18.690683          0.427049   24  
14998           161  19.791645          0.302257   23  
14999           512  36.215437          0.147363   34  

[15000 rows x 8 columns]

In [9]:
from sklearn.preprocessing import MinMaxScaler

In [11]:
for col in X:
    mm = MinMaxScaler()
    X[col] = mm.fit_transform(X[[col]])

In [12]:
X

Pregnancies  PlasmaGlucose  DiastolicBloodPressure  TricepsThickness  \
0         0.000000       0.858108                0.602151          0.313953   
1         0.571429       0.324324                0.741935          0.465116   
2         0.500000       0.479730                0.247312          0.523256   
3         0.642857       0.398649                0.580645          0.209302   
4         0.071429       0.277027                0.376344          0.232558   
...            ...            ...                     ...               ...   
14995     0.714286       0.141892                0.387097          0.453488   
14996     0.142857       0.195946                0.451613          0.232558   
14997     0.000000       0.331081                0.698925          0.418605   
14998     0.000000       0.594595                0.795699          0.127907   
14999     0.214286       0.472973                0.440860          0.465116   

       SerumInsulin       BMI  DiabetesPedigree       Age  
0          0.011465  0.668952          0.510511  0.000000  
1          0.028025  0.080352          0.036123  0.035714  
2          0.026752  0.616137          0.000438  0.035714  
3          0.369427  0.300831          0.541848  0.392857  
4          0.026752  0.645027          0.212047  0.017857  
...             ...       ...               ...       ...  
14995      0.207643  0.404713          0.031608  0.357143  
14996      0.196178  0.315380          0.352683  0.303571  
14997      0.054777  0.012956          0.156959  0.053571  
14998      0.187261  0.042056          0.100836  0.035714  
14999      0.634395  0.476156          0.031175  0.232143  

[15000 rows x 8 columns]

In [13]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3,random_state=123)

In [16]:
y_test

6958     1
7534     0
2975     1
3903     0
8437     0
        ..
8001     0
11631    0
8163     0
4063     0
2180     0
Name: Diabetic, Length: 4500, dtype: int64

In [22]:
from sklearn.linear_model import LogisticRegression

lmodel = LogisticRegression()

In [21]:
X_train

Pregnancies  PlasmaGlucose  DiastolicBloodPressure  TricepsThickness  \
5242      0.357143       0.371622                0.440860          0.267442   
12675     0.142857       0.527027                0.860215          0.441860   
6924      0.071429       0.290541                0.279570          0.313953   
12596     0.642857       0.317568                0.215054          0.255814   
12569     0.071429       0.716216                0.397849          0.395349   
...            ...            ...                     ...               ...   
5218      0.071429       0.358108                0.354839          0.337209   
12252     0.000000       0.270270                0.215054          0.441860   
1346      0.071429       0.243243                0.591398          0.023256   
11646     0.000000       0.844595                0.344086          0.034884   
3582      0.500000       0.520270                0.311828          0.325581   

       SerumInsulin       BMI  DiabetesPedigree       Age  
5242       0.094268  0.475776          0.727108  0.303571  
12675      0.024204  0.014693          0.002856  0.053571  
6924       0.035669  0.015235          0.385402  0.017857  
12596      0.198726  0.370881          0.037186  0.446429  
12569      0.045860  0.377402          0.023832  0.017857  
...             ...       ...               ...       ...  
5218       0.017834  0.631615          0.331919  0.035714  
12252      0.030573  0.658900          0.002269  0.232143  
1346       0.042038  0.094925          0.420795  0.053571  
11646      0.029299  0.608408          0.198198  0.017857  
3582       0.379618  0.042934          0.016499  0.000000  

[10500 rows x 8 columns]

In [23]:
model = lmodel.fit(X_train,y_train)

In [24]:
y_pred = model.predict(X_test)

In [25]:
y_pred

array([0, 0, 1, ..., 0, 0, 0])

In [27]:
from sklearn.metrics import accuracy_score, recall_score, precision_score, confusion_matrix, roc_curve

In [28]:
accuracy_score(y_test, y_pred)

0.7784444444444445

In [29]:
recall_score(y_test, y_pred)

0.589452603471295

In [30]:
precision_score(y_test, y_pred)

0.6980237154150197

In [31]:
confusion_matrix(y_test, y_pred)

array([[2620,  382],
       [ 615,  883]])

In [36]:
fpr, tpr, thresholds = roc_curve(y_test, y_pred)

In [37]:
fpr

array([0.       , 0.1272485, 1.       ])

In [38]:
tpr

array([0.       , 0.5894526, 1.       ])

In [39]:
from sklearn.metrics import roc_auc_score

In [40]:
roc_auc_score(y_test, y_pred)

0.7311020512359806

In [41]:
from sklearn.tree import DecisionTreeClassifier

In [42]:
dt = DecisionTreeClassifier()

In [44]:
dt_model = dt.fit(X_train, y_train)

In [45]:
y_preddt = dt_model.predict(X_test)

In [46]:
accuracy_score(y_test, y_preddt)

0.8944444444444445

In [47]:
recall_score(y_test, y_preddt)

0.8457943925233645

In [48]:
precision_score(y_test, y_preddt)

0.8385175380542687

In [49]:
roc_auc_score(y_test, y_preddt)

0.882257622644094

Regression

In [50]:
X

Pregnancies  PlasmaGlucose  DiastolicBloodPressure  TricepsThickness  \
0         0.000000       0.858108                0.602151          0.313953   
1         0.571429       0.324324                0.741935          0.465116   
2         0.500000       0.479730                0.247312          0.523256   
3         0.642857       0.398649                0.580645          0.209302   
4         0.071429       0.277027                0.376344          0.232558   
...            ...            ...                     ...               ...   
14995     0.714286       0.141892                0.387097          0.453488   
14996     0.142857       0.195946                0.451613          0.232558   
14997     0.000000       0.331081                0.698925          0.418605   
14998     0.000000       0.594595                0.795699          0.127907   
14999     0.214286       0.472973                0.440860          0.465116   

       SerumInsulin       BMI  DiabetesPedigree       Age  
0          0.011465  0.668952          0.510511  0.000000  
1          0.028025  0.080352          0.036123  0.035714  
2          0.026752  0.616137          0.000438  0.035714  
3          0.369427  0.300831          0.541848  0.392857  
4          0.026752  0.645027          0.212047  0.017857  
...             ...       ...               ...       ...  
14995      0.207643  0.404713          0.031608  0.357143  
14996      0.196178  0.315380          0.352683  0.303571  
14997      0.054777  0.012956          0.156959  0.053571  
14998      0.187261  0.042056          0.100836  0.035714  
14999      0.634395  0.476156          0.031175  0.232143  

[15000 rows x 8 columns]

In [51]:
X1 = X.drop("BMI", axis=1)
y1 = X["BMI"]

In [52]:
X1_train, X1_test, y1_train, y1_test = train_test_split(X1,y1,test_size=0.3,random_state=123)

In [54]:
y1_train

5242     0.475776
12675    0.014693
6924     0.015235
12596    0.370881
12569    0.377402
           ...   
5218     0.631615
12252    0.658900
1346     0.094925
11646    0.608408
3582     0.042934
Name: BMI, Length: 10500, dtype: float64

In [55]:
from sklearn.linear_model import LinearRegression

In [56]:
linr = LinearRegression()

In [57]:
modelreg = linr.fit(X1_train, y1_train)

In [58]:
y1_pred = modelreg.predict(X1_test)

In [59]:
y1_pred

array([0.36446283, 0.33601014, 0.36988398, ..., 0.34492006, 0.35142412,
       0.32915367])

In [60]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [61]:
mean_absolute_error(y1_test, y1_pred)

0.2256932477379724

In [62]:
mean_squared_error(y1_test, y1_pred)

0.06440592697262516

In [63]:
r2_score(y1_test, y1_pred)

0.01687529917111552

In [64]:
X1_train

Pregnancies  PlasmaGlucose  DiastolicBloodPressure  TricepsThickness  \
5242      0.357143       0.371622                0.440860          0.267442   
12675     0.142857       0.527027                0.860215          0.441860   
6924      0.071429       0.290541                0.279570          0.313953   
12596     0.642857       0.317568                0.215054          0.255814   
12569     0.071429       0.716216                0.397849          0.395349   
...            ...            ...                     ...               ...   
5218      0.071429       0.358108                0.354839          0.337209   
12252     0.000000       0.270270                0.215054          0.441860   
1346      0.071429       0.243243                0.591398          0.023256   
11646     0.000000       0.844595                0.344086          0.034884   
3582      0.500000       0.520270                0.311828          0.325581   

       SerumInsulin  DiabetesPedigree       Age  
5242       0.094268          0.727108  0.303571  
12675      0.024204          0.002856  0.053571  
6924       0.035669          0.385402  0.017857  
12596      0.198726          0.037186  0.446429  
12569      0.045860          0.023832  0.017857  
...             ...               ...       ...  
5218       0.017834          0.331919  0.035714  
12252      0.030573          0.002269  0.232143  
1346       0.042038          0.420795  0.053571  
11646      0.029299          0.198198  0.017857  
3582       0.379618          0.016499  0.000000  

[10500 rows x 7 columns]

In [65]:
from sklearn.cluster import KMeans

In [67]:
kmn = KMeans(n_clusters = 3)

In [68]:
modelkmn = kmn.fit(X1_train)

/home/ubuntu/environments/hpepyspark/lib/python3.8/site-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


In [69]:
y2_pred = modelkmn.predict(X1_test)

In [70]:
modelkmn.cluster_centers_

array([[0.55267694, 0.43457928, 0.50980323, 0.25668977, 0.16583239,
        0.14678995, 0.09584748],
       [0.06241774, 0.41598828, 0.50151841, 0.24252757, 0.1392354 ,
        0.13180068, 0.05775729],
       [0.25873914, 0.46458835, 0.52733799, 0.2761532 , 0.19625462,
        0.1732975 , 0.53018287]])

In [71]:
y2_pred

array([2, 1, 0, ..., 1, 1, 1], dtype=int32)

In [73]:
from sklearn.metrics import silhouette_score, rand_score, adjusted_rand_score

In [74]:
silhouette_score(X1_test, y2_pred)

0.2139772626658987

In [75]:
kmn1 = KMeans(n_clusters = 3)

In [76]:
modelkmn1 = kmn1.fit(X1_train)

/home/ubuntu/environments/hpepyspark/lib/python3.8/site-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


In [77]:
y2_pred1 = modelkmn1.predict(X1_test)

In [78]:
rand_score (y2_pred, y2_pred1)

0.9971543305919834

In [79]:
adjusted_rand_score(y2_pred, y2_pred1)

0.994024687001455